### ISSUE TITLE
Invert stereoscopic 3D mode (flip eyes)

### ISSUE THREAD

**Issue by 3drpi** [huceke/omxplayer#261] opened 2016-03-20 15:39 UTC
Invert stereoscopic 3D mode (flip eyes) is available in omxplayer like an option file? 
-M  --allow-mvc             Allow decoding of both views of MVC stereo stream.
I need to display only the right eye

**Comment by popcornmix** [comment] 2016-03-21 13:55
This repo is dead. Duplicate of https://github.com/popcornmix/omxplayer/issues/438

**Closed as completed by popcornmix** 2016-03-21 13:55 UTC
