### ISSUE TITLE
Graphical problem in the two black bar in the top and bottom

### ISSUE THREAD

**Issue by iz8mbw** [huceke/omxplayer#110] opened 2013-02-04 18:16 UTC
Hi.
With omxplayer I have a graphical problem for movies that has an aspect ratio different from 16:9.
I use this release omxplayer_0.2.4~git20130203~ba548f0d_armhf.deb from the site http://omxplayer.sconde.net/

I try to explane the problem:

My Raspberry use 1920x1080p @ 50 Hz (on HDMI), it's OK. My TV is 16:9.
If I try to play for example a 21:9 movie (so with the two black bar in the top and bottom) @ 24 frame per second and I use -r option the Raspberry (and so my TV) switch to 1920x1080p @ 24 Hz, OK no problem I see the movie without problems.
But if the 21:9 movie is @ 25 frame per second (or @ 30 frame per second) and I use or not use -r option my TV switch back to 1920x1080p @ 50 Hz and I can see the movie but with graphical error, to explane it better: the movie is OK but in the two black bar in the top and bottom I see the old text of the Raspberry startup (so the two black bar in the top and bottom are not fully black).
It happens also with 4:3 movies but the problem, obviously, will be in the two black bar in the left and right.
To understand better the problem, in attach I give to you 3 image:

21-9_error_in_the_top.jpg -> graphical error in the top
21-9_error_in_the_bottom.jpg -> graphical error in the bottom
4-3_error_in_the_left.jpg -> graphical error in the left

In conclusion, the error happens always if omxplayer will not adjust framerate/resolution to video, example:

50Hz Raspberry output -> 24fps movie -r option enabled -> No problem (-r option will workaround the problem)
50Hz Raspberry output -> 24fps movie -r option disabled -> Yes problem
50Hz Raspberry output -> 25fps (or 30fps) movie -r option disabled or enabled -> Yes problem (-r option, if enabled, will not workaround the problem)

So only if omxplayer will refresh the output video I will not see the graphical problem.

Why I can see that errors?
Is it possible to upgrade omxplayer to "force" a video refresh just before to play a movie?

I hope that I was clear to explane the problem.
Thanks!

Fabio
![21-9_error_in_the_top](https://f.cloud.github.com/assets/3474082/124607/dba3fdc0-6ef6-11e2-8cc3-cf97aa5ef4a7.jpg)
![21-9_error_in_the_bottom](https://f.cloud.github.com/assets/3474082/124609/efb8aa86-6ef6-11e2-919c-f9ae94f5ecd0.jpg)
![4-3_error_in_the_left](https://f.cloud.github.com/assets/3474082/124610/01f6d678-6ef7-11e2-9567-d687aef91a4e.jpg)

**Comment by popcornmix** [comment] 2013-02-04 22:25
Duplicate of https://github.com/huceke/omxplayer/issues/44

**Closed as completed by popcornmix** 2013-02-04 22:25 UTC
