### ISSUE TITLE
Please support newer versions of ffmpeg.

### ISSUE THREAD

**Issue by TamaraWijsman** [huceke/omxplayer#155] opened 2013-04-13 12:25 UTC
8c51ea54897c2d8671b38efecc1422ad4ad344f9 is from September 20, 2013 which is about half a year ago; could you update the code to work with newer versions of ffmpeg? Thank you in advance.

**Comment by popcornmix** [comment] 2013-04-13 12:57
It's been tried, but not currently working.
Duplicate of https://github.com/huceke/omxplayer/issues/150

**Closed as completed by popcornmix** 2013-04-13 12:57 UTC
