### ISSUE TITLE
Each time one starts/ends a sound there is a loud bang

### ISSUE THREAD

**Issue by calledit** [huceke/omxplayer#76] opened 2012-11-17 20:44 UTC
I have google and looked in to it a bit. (thinking i could fix it but i have now realized there is way to much code to get my head around)

Apparently this was fixed in the alsa driver a couple of weeks ago. (so it is fixable somehow)
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=24&t=12070

Anyway:
My idea initial was to make shore the sound input never goes down. Just make shore there is "silent" data going out when there is nothing other going on.

Not shore if its a good idea.
Just throwing it out there.

**Comment by popcornmix** [comment] 2013-03-25 22:03
Duplicate of https://github.com/huceke/omxplayer/issues/106
Should be fixed.

**Closed as completed by popcornmix** 2013-03-25 22:03 UTC
