### ISSUE TITLE
Omxplayer play rtsp over tcp 

### ISSUE THREAD

**Issue by tulkas85** [huceke/omxplayer#242] opened 2015-03-23 09:58 UTC
I play rtsp video stream on Raspberry Pi 2, and I have some video glitches in image, I think it's network problem, maybe some packet lost

I run omxplayer using :
omxplayer --win '0 0 960 540' -o hdmi --layer 6 rtsp://xxx:xxx@xxx.xx.xx.xx/h264/ch1/main/av_stream

using tcpdump I see that received packet is UDP , maybe using TCP I can solve this issue...
Can omxplayer play rtsp over tcp ?

**Comment by popcornmix** [comment] 2015-03-23 13:26
omxplayer will support what ffmpeg supports.
But rtsp as a standard uses udp as a default and would only be able to suport tcp/ip if the server supports that (e.g. though a different URL), but I suspect that won't be possible.

**Comment by tulkas85** [comment] 2015-03-23 13:53
so there isn't an option like vlc :
option->input/codecs-> demuxer->Rtsp-> Use RTP over RTSP (TCP)

enabling this option, I have rtp/tcp packet instead udp using same rtsp url

**Comment by popcornmix** [comment] 2015-03-23 14:17
Are you able to build omxplayer?
It seems there is an option in ffmpeg to set "-rtsp_transport tcp", but you need to rebuild omxplayer to set it.

**Comment by tulkas85** [comment] 2015-03-23 14:42
I could try to build, can you tell me files to edit please ?

**Comment by popcornmix** [comment] 2015-03-23 14:51
This is the patch I'm suggesting. Eventually we'll need to add a command line parameter, but would like to know if this has any effect first:

```
diff --git a/OMXReader.cpp b/OMXReader.cpp
index 4f61f6d..b30290f 100644
--- a/OMXReader.cpp
+++ b/OMXReader.cpp
@@ -197,6 +197,12 @@ bool OMXReader::Open(std::string filename, bool dump_format, bool live /* =false
           av_dict_set(&d, "user_agent", user_agent.c_str(), 0);
        }
     }
+    else if(m_filename.substr(0,7) == "rtsp://" || m_filename.substr(0,6) == "rtp://")
+    {
+        int ret = av_dict_set(&d, "rtsp_transport", "tcp", 0);
+        assert(ret == 0);
+    }
+
     CLog::Log(LOGDEBUG, "COMXPlayer::OpenFile - avformat_open_input %s ", m_filename.c_str());
     result = m_dllAvFormat.avformat_open_input(&m_pFormatContext, m_filename.c_str(), iformat, &d);
     if(av_dict_count(d) == 0)
```

**Comment by tulkas85** [comment] 2015-03-23 15:49
Can you tell me how can I compile it on raspberry pi 2 without overwrite existing and working omxplayer installation, please ?

**Comment by tulkas85** [comment] 2015-03-30 14:29
ok, I try your code and works. Now rtsp stream run over tcp.
I add --tcp parameter too in my installed version.

Thank you

**Comment by popcornmix** [comment] 2015-03-30 14:46
I was wondering about adding a more generic command line option. E.g.

```
omxplayer --dict rtsp_transport=tcp rtsp://foo.bar
```

As there are lots of magic "av_dict_set" options that ffmpeg uses.

**Comment by tulkas85** [comment] 2015-03-30 15:22
yes, It's certainly a better idea

**Comment by frozengopher** [comment] 2015-07-28 16:20
I applied the patch you suggested and rebuilt omxplayer because I had a similar situation. My security camera system supports RTSP over TCP, and so the patch works great. However, with plain RTSP using UDP, I was getting vertical stripes in the lower part of the picture, apparently because one or more UDP packets gets missed during the I-frame data. This problem has been mentioned by others in other web forums. Yet with the patch and the additional overhead of TCP, everything is fine, and running top shows omxplayer only using 12% - 17% of the CPU on my Pi2 Raspbian, overclocked 1000/500/500. Is there some way the performance with ordinary RTSP can be improved? Is it some other component of Raspbian unable to buffer all the UDP packets, or is it omxplayer?

**Comment by popcornmix** [comment] 2015-07-29 15:30
Hard to be sure. Somewhere between where the packets originate and omxplayer UDP packets are being dropped. In theory UDP packets are allowed to be dropped by any component in network.

How is camera connected to Pi? Any wifi stages. Just a single router, or are there other switches?

**Comment by frozengopher** [comment] 2015-07-29 15:41
No Wifi stages. Camera goes through a switch, then router, then to Pi. By the way, when I view the RTSP stream on a computer with VLC using the normal UDP, it works fine. That also goes through a second switch on the computer side of the router.

**Comment by popcornmix** [comment] 2015-07-29 15:45
Can you run iperf betwen pi and computer connected to same switch as camera.
Might confirm what the maximum bitrate you can send and what the packet loss is.

Is any of your equipment GigE? I wonder if that creates a funnel effect when data is sent faster than it can be received.

**Comment by frozengopher** [comment] 2015-07-29 17:48
No Wifi, No GigE, here is iperf report:
iperf -s -u

---

Server listening on UDP port 5001
Receiving 1470 byte datagrams
UDP buffer size:  160 KByte (default)

---

[  3] local 192.168.99.25 port 5001 connected with 192.168.99.14 port 1032
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0-10.0 sec  83.1 MBytes  69.6 Mbits/sec   0.988 ms    0/59266 (0%)
[  3]  0.0-10.0 sec  1 datagrams received out-of-order

**Comment by falaca** [comment] 2016-01-20 04:57
Any chance that this will be implemented soon? I have (I think) the same problem - vertical stripes on the bottom 1/4 of the screen, especially at 1080p (but sometimes also with 720p). I'm streaming via RTSP from an Axis IP camera. Here's what it looks like: https://www.dropbox.com/s/8s6m1ssi1wowbky/IMAG0096.jpg?dl=0

Can anybody confirm that it is the same effect? When I have a chance I'll see if I can re-compile omxplayer with that patch and see if it makes a difference.

FWIW, I've found a few other users apparently describing the same issue with ffmpeg, reportedly fixed by switching to TCP:
http://comments.gmane.org/gmane.comp.video.ffmpeg.issues/11899
http://foscam.us/forum/rtsp-streaming-problem-t6961.html
https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=1000

**Comment by falaca** [comment] 2016-01-20 13:26
It occurred to me today that when ffplay fails to establish an RTSP stream over UDP, it falls back to TCP instead, so I thought omxplayer might follow the same behaviour. I went ahead and blocked UDP traffic from the camera with iptables, ran omxplayer, and after a few extra seconds of delay (since it first tries UDP but fails to receive the response) the video started streaming over TCP (confirmed via  tcpdump). The vertical lines are now gone!

It took months but I'm glad to have finally found a fix for the problem. Thanks @tulkas85! It would be great to see this command-line parameter implemented.

**Comment by falaca** [comment] 2016-01-20 13:36
According to this discussion, it looks like the problem relates to the UDP buffer size: ZoneMinder/ZoneMinder#811

Based on the comments, an alternative solution is to increase the buffer size.

**Comment by frozengopher** [comment] 2016-01-20 14:47
falaca, Yes I can confirm your photo shows the same effect I experienced.

**Comment by falaca** [comment] 2016-02-10 22:00
@popcornmix I tested this camera on my laptop using ffplay (both with ffmpeg 2.4.3 and 2.8.1), and I don't get any corruption. But I have 2 Raspberry Pi Model Bs, and 1 Raspberry Pi 2, and they all give the same kind of corruption like in the photo I shared above.

I wonder if this could have anything to do with the network driver? Maybe packets are being received out of order? Is there any way I can test for that?

When I test UDP bandwidth with iperf between 2 raspberry pis, I get no packet loss all the way up to around 73Mbps (that seems to be the fastest that it can go), but there's always 1 datagram received out of order.

**Comment by falaca** [comment] 2016-02-10 22:20
OK I installed ffmpeg 2.8.6 on my laptop, and it still plays without issue. But ffmplay always throws out these errors at the beginning of the stream:

```
[rtsp @ 0x7f18580008c0] max delay reached. need to consume packet   
[h264 @ 0x7f1858004f80] RTP: missed 24 packets
[h264 @ 0x7f1858004f80] error while decoding MB 63 10, bytestream -8
[h264 @ 0x7f1858004f80] concealing 6946 DC, 6946 AC, 6946 MV errors in P frame
[rtsp @ 0x7f18580008c0] max delay reached. need to consume packet   
[h264 @ 0x7f1858004f80] RTP: missed 304 packets
Input #0, rtsp, from 'rtsp://root:ziedama456@10.10.20.11/axis-media/media.amp?videocodec=h264&streamprofile=Quality&fps=30':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.033333, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 30 tbr, 90k tbn, 180k tbc
[h264 @ 0x7f1858136280] error while decoding MB 63 10, bytestream -10
[h264 @ 0x7f1858136280] concealing 6946 DC, 6946 AC, 6946 MV errors in P frame
[swscaler @ 0x7f18502e9960] deprecated pixel format used, make sure you did set range correctly
[h264 @ 0x7f18580c4e60] error while decoding MB 40 34, bytestream -7
[h264 @ 0x7f18580c4e60] concealing 4089 DC, 4089 AC, 4089 MV errors in P frame
```
So there is some momentary corruption right at the beginning, but then it continues normally after that. Could this have anything to do with the problem?

Meanwhile, I'll try to collect some packets on one of the raspberry pis with tcpdump, and check it out in wireshark to see if any packets are being received out of order.

**Comment by falaca** [comment] 2016-02-10 22:20
OK I installed ffmpeg 2.8.6 on my laptop, and it still plays without issue. But ffmplay always throws out these errors at the beginning of the stream:

```
[rtsp @ 0x7f18580008c0] max delay reached. need to consume packet   
[h264 @ 0x7f1858004f80] RTP: missed 24 packets
[h264 @ 0x7f1858004f80] error while decoding MB 63 10, bytestream -8
[h264 @ 0x7f1858004f80] concealing 6946 DC, 6946 AC, 6946 MV errors in P frame
[rtsp @ 0x7f18580008c0] max delay reached. need to consume packet   
[h264 @ 0x7f1858004f80] RTP: missed 304 packets
Input #0, rtsp, from 'rtsp://10.10.20.11/axis-media/media.amp?videocodec=h264&streamprofile=Quality&fps=30':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.033333, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 30 tbr, 90k tbn, 180k tbc
[h264 @ 0x7f1858136280] error while decoding MB 63 10, bytestream -10
[h264 @ 0x7f1858136280] concealing 6946 DC, 6946 AC, 6946 MV errors in P frame
[swscaler @ 0x7f18502e9960] deprecated pixel format used, make sure you did set range correctly
[h264 @ 0x7f18580c4e60] error while decoding MB 40 34, bytestream -7
[h264 @ 0x7f18580c4e60] concealing 4089 DC, 4089 AC, 4089 MV errors in P frame
```
So there is some momentary corruption right at the beginning, but then it continues normally after that. Could this have anything to do with the problem?

Meanwhile, I'll try to collect some packets on one of the raspberry pis with tcpdump, and check it out in wireshark to see if any packets are being received out of order.

**Comment by falaca** [comment] 2016-02-11 04:18
Tonight I captured some traffic with tcpdump and analyzed it in wireshark (it can decode the RTP packets to show the sequence numbers). The results:

1) With unicast UDP, there is absolutely no packet loss, and packets are received in the correct order
2) With multicast UDP, throughput is capped at around 6Mbps, so there is severe packet loss (this particular stream was around 14Mbps)

I had observed before that the "smearing" occurs when the bit rate exceeds around 6Mbps. I don't know if it's a coincidence that the multicast traffic seemed to be capped at around that limit.

**Comment by falaca** [comment] 2016-02-20 21:08
After building a modified omxplayer to set the buffer_size and fifo_size in ffmpeg (using av_dict_set), I was able to solve the corruption. I also had to increase the kernel's UDP receive buffer size by setting net.core.rmem_max.

I was able to confirm via netstat -s (RcvbufErrors) that the kernel was dropping UDP datagrams because they weren't being processed fast enough at the application layer. After making the above modifications, the kernel stopped dropping datagrams. (Interesting that wireshark was capturing the dropped unicast datagrams, but not the dropped multicast datagrams)

@popcornmix It would be nice if you could add the av_dict_set option. I'd consider adding it myself if I find the time - would you accept a pull request?

**Comment by popcornmix** [comment] 2016-02-20 21:15
Yes, sounds okay. Presumably would like very like https://github.com/popcornmix/omxplayer/pull/429

**Comment by falaca** [comment] 2016-03-14 07:37
Thanks @popcornmix that was helpful. I wrote the patch and created the PR referenced above.

And btw, any idea when the package will be updated in the raspbian repo?

**Comment by tdicks** [comment] 2016-06-08 11:14
Further to @falaca's post above, any idea when the raspbian repo will be updated? We're setting up an RTSP stream to an RPi with omxplayer and are encountering the video corruption highlighted above.

**Comment by popcornmix** [comment] 2016-06-08 11:17
I believe the raspbian repo version of omxplayer includes the `--lavfdopts` and `--avdict` flags.
Are you up to date? What does `omxplayer -v` report?

**Comment by tdicks** [comment] 2016-06-08 12:04
Here's the -v output:

```
        Build date: Sat, 12 Sep 2015 00:49:19 +0000
        Version   : d99bd86 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```

It's a fresh download of Raspbian with apt-get upgrade run. I'm going to try building this using the included shellscript and see how I get on.

**Comment by popcornmix** [comment] 2016-06-08 12:12
Raspbian Jessie? You should have:

```
        Build date: Fri, 06 May 2016 14:07:54 +0000
        Version   : 6c90c75 [master]
        Repository: https://github.com/popcornmix/omxplayer.git
```

It should match the deb file here: http://omxplayer.sconde.net/

**Comment by tdicks** [comment] 2016-06-08 13:08
Yes it was Jessie. I pulled down the .deb and installed it through dpkg which gave me the version you have there. The command switches I needed are present and the RTSP stream is no longer screwy.

Thanks a lot for your help!

**Closed as completed** 2016-06-08 13:19 UTC

**Comment by john-devaar-doe** [comment] 2019-05-16 17:31
It is May of 2019. If you are still having problems with omxplayer and an RTSP URL, then stop for one second and do the following:
Surround the RTSP URL in double-quotes. If you are doing this from inside a shell script, please escape the quotes with a back-slash...and run the script again. I was using omxplayer as part of a script to display a bunch of IP Cameras on a display and wasted several days with this issue. For some reason, I did not need to add double-quotes on the URL I used on the lab to test the code, but when I took the system to the customer's premises, it simply did not work. What is worse, despite writing the script to provide detailed error messages, I could not generate any log entry to troubleshoot the problem. Here is the command I used to get everything back on track. I hope this will help someone in a similar situation:
screen -dmS bottom_right sh -c 'omxplayer --win \"1280 720 1920 1080\" \"rtsp://[USER_NAME]:[PASSWORD_WITH_NON_ALPHANUMERIC_CHARS]@[IP_ADDRESS]:[PORT][CAM_SPECIFIC_API_CALL]]\" --live -n -1'
