### ISSUE TITLE
Network Video stream stutter

### ISSUE THREAD

**Issue by akshaylad** [huceke/omxplayer#139] opened 2013-03-20 16:29 UTC
I am using my raspberry pi as video decoder to decode 500kb h264 stream but it stutters on playback i changed advanced settings file and increased cache memory but it didnt help ... 

I tested omxplayer in Local Area Network and it decodes perfectly the stream. But however when i try to connect the same stream over Internet the video plays fine for few seconds and start stuttering and stops. Bandwidth is not an issue as i am having 1gbps fiber link. The same stream if i open on a pc with vlc it perfectly plays.if i try to reencode that stream in vlc and send it to omxplayer over lan it plays fine

**Comment by popcornmix** [comment] 2013-03-20 17:41
Looks like a duplicate of https://github.com/huceke/omxplayer/issues/109

**Closed as completed by popcornmix** 2013-03-20 17:41 UTC

**Comment by akshaylad** [comment] 2013-03-20 17:49
but has anyone resolved the issue?

On Wed, Mar 20, 2013 at 11:11 PM, popcornmix notifications@github.comwrote:

> Look like a duplicate of #109https://github.com/huceke/omxplayer/issues/109
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/huceke/omxplayer/issues/139#issuecomment-15191422
> .

## 

_Akshay Lad_
_(Technical Asst. Systems)_
_NIT-GOA_
_08007081745_
