### ISSUE TITLE
RASPBERRY 3 OMX PLAYER DONT COMPILE

### ISSUE THREAD

**Issue by romuald-maillet** [huceke/omxplayer#272] opened 2016-11-03 15:05 UTC
Hello everybody,

It is impossible to compile omxplayer directly on the raspberry 3.

Make ffmpeg -> LIB SMB CLIENT not found !!!
So i desactivate it in makefile.ffmpeg and after compilation ffmpeg is ok.
#			--enable-libsmbclient \
#			--enable-libssh \
#			--enable-nonfree \
#			--enable-openssl \

Then make -> there is Command not found. So i comment and modify the makefile with
else
#BUILDROOT	:=/opt/bcm-rootfs
#SDKSTAGE	:=/opt/bcm-rootfs
#TARGETFS	:=/opt/bcm-rootfs
#TOOLCHAIN	:=/home/dc4/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/
#HOST		:=arm-linux-gnueabihf
#SYSROOT		:=$(TOOLCHAIN)/arm-bcm2708hardfp-linux-gnueabi/sysroot
#SYSROOT		:=/opt/bcm-rootfs

BUILDROOT	:=/usr/local/src/omxplayer
SDKSTAGE	:=
TARGETFS	:=
TOOLCHAIN	:=/usr/
HOST		:=arm-linux-gnueabihf
#SYSROOT		:=$(TOOLCHAIN)/arm-bcm2708hardfp-linux-gnueabi/sysroot
SYSROOT		:=

Then make and result of this command is 
/usr//bin/arm-linux-gnueabihf-g++ --sysroot= -isystem/include -pipe -mfloat-abi=hard -mcpu=arm1176jzf-s -fomit-frame-pointer -mabi=aapcs-linux -mtune=arm1176jzf-s -mfpu=vfp -Wno-psabi -mno-apcs-stack-check -g -mstructure-size-boundary=32 -mno-sched-prolog -std=c++0x -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -DTARGET_LINUX -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CMAKE_CONFIG -D__VIDEOCORE4__ -U_FORTIFY_SOURCE -Wall -DHAVE_OMXLIB -DUSE_EXTERNAL_FFMPEG  -DHAVE_LIBAVCODEC_AVCODEC_H -DHAVE_LIBAVUTIL_OPT_H -DHAVE_LIBAVUTIL_MEM_H -DHAVE_LIBAVUTIL_AVUTIL_H -DHAVE_LIBAVFORMAT_AVFORMAT_H -DHAVE_LIBAVFILTER_AVFILTER_H -DHAVE_LIBSWRESAMPLE_SWRESAMPLE_H -DOMX -DOMX_SKIP64BIT -ftree-vectorize -DUSE_EXTERNAL_OMX -DTARGET_RASPBERRY_PI -DUSE_EXTERNAL_LIBBCM_HOST -isystem/opt/vc/include -isystem/usr/include -isystem/opt/vc/include/interface/vcos/pthreads -Ipcre/build -Iboost-trunk -Ifreetype2/include -I./ -Ilinux -Iffmpeg_compiled/usr/local/include/ -I /usr/include/dbus-1.0 -I /usr/lib/arm-linux-gnueabihf/dbus-1.0/include -c OMXPlayerSubtitles.cpp -o OMXPlayerSubtitles.o -Wno-deprecated-declarations
In file included from OMXPlayerSubtitles.cpp:21:0:
SubtitleRenderer.h:31:22: fatal error: ft2build.h: Aucun fichier ou dossier de ce type
 #include <ft2build.h>
                      ^
compilation terminated.
Makefile:46: recipe for target 'OMXPlayerSubtitles.o' failed
make: *** [OMXPlayerSubtitles.o] Error 1

Can you do a makefile that compile directly on raspberry without cross compile complication

Thank You and have a nive day
Romuald

**Comment by popcornmix** [comment] 2016-11-04 14:07
Duplicate of https://github.com/popcornmix/omxplayer/issues/497

**Closed as completed by popcornmix** 2016-11-04 14:07 UTC
