### ISSUE TITLE
Full screen does not exit properly on Pi

### ISSUE THREAD

**Issue by bethebeer** [huceke/omxplayer#63] opened 2012-10-08 03:01 UTC
Whenever I use the "-r" option for full screen, when I exit the video, or it ends, I just have a black screen.  The only way to fix this is by typing in "sudo reboot" or pulling the plug, if I have clicked out of the terminal.  I am running Raspbian on a Raspberry Pi.  Not sure if the version used in Raspbian is different than the git.

Thanks

**Comment by KenT2** [comment] 2012-10-08 07:57
A solution is in issue 44

**Comment by popcornmix** [comment] 2012-10-08 11:25
Duplicate of #44

**Closed as completed by popcornmix** 2012-10-08 11:25 UTC

**Comment by bethebeer** [comment] 2012-10-08 17:00
Is "fbset -depth 8 && fbset -depth 16" supposed to be typed after the video ends? Or is it supposed to be typed in before you start it? If it is in the start, does order matter?

**Comment by popcornmix** [comment] 2012-10-09 09:11
After. Ideally make a wrapper script that launches omxplayer, then does the fbset commands.
This may be suitable:
https://raw.github.com/huceke/omxplayer/master/omxplayer

**Comment by skgsergio** [comment] 2012-10-09 09:14
I must fix this on my wrapper script...
