### ISSUE TITLE
how to solve the delay problem?

### ISSUE THREAD

**Issue by chenyayun** [huceke/omxplayer#216] opened 2014-03-06 09:16 UTC
hello 
today , when play RTMP use the omxplayer , it has about 4-5seconds delay. 
I also use the "video_size" and "video_queue", it does nothing about the problem.
do you know!

**Comment by popcornmix** [comment] 2014-03-06 11:31
Have you got a public url I can connect to?
Are you using the --live option?

**Comment by chenyayun** [comment] 2014-03-06 12:37
no, I use a rtmp stream internal. 
--live option ? I have not use, the option means what?

**Comment by popcornmix** [comment] 2014-03-06 14:06
```
              --live                    Set for live tv or vod type stream
```

**Comment by chenyayun** [comment] 2014-03-06 14:38
Thanyou for your repeat.
But I really could not find the "--live" opt int the omxplayer.cpp.

**Comment by popcornmix** [comment] 2014-03-06 15:00
Well, that's because this is an obsolete repo. You should use code from:
https://github.com/popcornmix/omxplayer
and binaries from:
http://omxplayer.sconde.net/

Can you test the latest code, and if there's still a problem open an issue here:
https://github.com/popcornmix/omxplayer

**Comment by chenyayun** [comment] 2014-03-06 15:13
ok, I will have a try!

**Comment by chenyayun** [comment] 2014-03-10 03:39
Just now , I have played RTMP stream. 
720P     delay time < 1s
1080P   delay time = 4s

the result is same to the source code of "huceke / omxplayer"
why ?

**Comment by popcornmix** [comment] 2014-03-10 13:15
Duplicate of https://github.com/popcornmix/omxplayer/issues/156

**Closed as completed by popcornmix** 2014-03-10 13:15 UTC
