### ISSUE TITLE
PCM audio always downsampled to stereo on Raspberry Pi

### ISSUE THREAD

**Issue by marklam** [huceke/omxplayer#125] opened 2013-02-25 21:00 UTC
My guess is it's something to do with line 460 in PCMRemap.cpp
 m_channelLayout  = PCM_LAYOUT_2_0;

But trying to play back 4.0 FLAC gives
 00:00:00 T:0    INFO: CPCMRemap: I channel map: FL,FR,BL,BR
 00:00:00 T:0   DEBUG: pcm->nPortIndex     : 0
 00:00:00 T:0   DEBUG: pcm->eNumData       : 0
 00:00:00 T:0   DEBUG: pcm->eEndian        : 1
 00:00:00 T:0   DEBUG: pcm->bInterleaved   : 1
 00:00:00 T:0   DEBUG: pcm->nBitPerSample  : 16
 00:00:00 T:0   DEBUG: pcm->ePCMMode       : 0
 00:00:00 T:0   DEBUG: pcm->nChannels      : 4
 00:00:00 T:0   DEBUG: pcm->nSamplingRate  : 96000
 00:00:00 T:0   DEBUG: OMX_AUDIO_ChannelLF
 00:00:00 T:0   DEBUG: OMX_AUDIO_ChannelRF
 00:00:00 T:0   DEBUG: OMX_AUDIO_ChannelLR
 00:00:00 T:0   DEBUG: OMX_AUDIO_ChannelRR
 00:00:00 T:0   DEBUG: pcm->nPortIndex     : 0
 00:00:00 T:0   DEBUG: pcm->eNumData       : 0
 00:00:00 T:0   DEBUG: pcm->eEndian        : 1
 00:00:00 T:0   DEBUG: pcm->bInterleaved   : 1
 00:00:00 T:0   DEBUG: pcm->nBitPerSample  : 16
 00:00:00 T:0   DEBUG: pcm->ePCMMode       : 0
 00:00:00 T:0   DEBUG: pcm->nChannels      : 2
 00:00:00 T:0   DEBUG: pcm->nSamplingRate  : 96000
 00:00:00 T:0   DEBUG: OMX_AUDIO_ChannelLF
 00:00:00 T:0   DEBUG: OMX_AUDIO_ChannelRF
 ...
 00:00:00 T:0   DEBUG: COMXAudio::Initialize Ouput bps 16 samplerate 96000 channels 2 device hdmi buffer size 1536000 bytes per second 768000 passthrough 0 hwdecode 0
 00:00:00 T:0   DEBUG: COMXAudio::Initialize Input bps 16 samplerate 96000 channels 4 device hdmi buffer size 1536000 bytes per second 768000 passthrough 0 hwdecode 0

**Comment by fastcat** [comment] 2013-02-25 22:52
What are you hoping for it to do?  There's nowhere the Pi can output such a stream.

The analog output only has stereo of course.

Digital audio over HDMI (AFAIK) only supports stereo PCM, or an encoded format like Dolby Digital (AC3) or DTS.  Transcoding multi-channel PCM to AC3 or DTS requires a) a license (and I don't think it's a cheap one, probably several times the cost of the Pi itself), and b) probably a much more powerful CPU than the Pi has to do it in realtime.  Even if the Pi's GPU is powerful enough to do it, I doubt anyone has written an AC3 encoder for any GPU, much less for a consumer-focused chip like is in the Pi.

The best omxplayer can do with 4 channel PCM is to downmix it to stereo in Dolby Pro Logic form so that you can recover at least some of the extra channels in analog space given the right mode on your receiver.  I was pretty sure that's what omxplayer already does, in fact, though maybe that's only with AC3 and DTS streams.

**Comment by popcornmix** [comment] 2013-02-25 23:23
@Churten 
HDMI can support multichannel PCM.
There are some limitations - it's only possible with high enough pixel clocks (generally higher resolutions) and it's not supported by optical out (e.g. from TV).

The hello_pi/hello_audio demo can be edited quite easily to support multichannel PCM.
The more difficult case is all the new conversions that this opens up:
E.g. source is mono/stereo/2.1/5.1/7.1 etc, receiver is stereo/5.1/7.1 etc.

**Comment by fastcat** [comment] 2013-02-25 23:31
I stand corrected, learn something new every day :)

**Comment by marklam** [comment] 2013-02-27 13:03
Thanks @popcornmix, I was beginning to question whether I'd dreamed it, but I was fairly sure I was able to play back the 4.0 FLAC file with the xbmc build from this blog (I think I used the SD card image).
http://selfprogramming.bplaced.net/index.php/2012/10/05/new-xbmcdeb-mainline-tree-for-raspberry-pi/
which I found from the Raspberry Pi forum post:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=12455&start=125

**Comment by popcornmix** [comment] 2013-02-27 13:47
@marklam 
No, you did imagine that. xbmc has never supported more than stereo PCM output.
For both omxplayer and xbmc, the only possibility to get multichannel output is ac3 or dts passthrough.

**Comment by marklam** [comment] 2013-02-27 21:31
Wow, wonder what I did to convince myself so thoroughly that there were 4 channels PCM shown on my amp :-(
As for up/downmixes etc would there be a problem with output channels = min(input channels, out device capability)

**Comment by popcornmix** [comment] 2013-02-27 21:36
That would be a first target. Unfortunately not all audio formats puts the channels in the same order, so you'll probably find the left channel comes out of the sub woofer.

**Comment by popcornmix** [comment] 2013-06-22 16:19
Duplicate of https://github.com/huceke/omxplayer/issues/94

**Closed as completed by popcornmix** 2013-06-22 16:19 UTC
