### ISSUE TITLE
Audio Strange

### ISSUE THREAD

**Issue by ginobvhc** [huceke/omxplayer#193] opened 2013-07-28 21:12 UTC
I install the las version from archlinux https://aur.archlinux.org/packages/omxplayer-git/?setlang=es
And the sound -o local  is distorted
if you need more info please contact with me at ginobvhc [at] gmail [dot] com
i will like to help

**Comment by popcornmix** [comment] 2013-07-29 09:48
Duplicate of https://github.com/popcornmix/omxplayer/issues/25

**Closed as completed by popcornmix** 2013-07-29 09:48 UTC
