### ISSUE TITLE
Longtime playing rstp stream problem

### ISSUE THREAD

**Issue by xapepam** [huceke/omxplayer#202] opened 2013-09-27 08:17 UTC
Im use Raspberry to stream RSTP video stream from IP camera, then Raspberry take this stream to analog in on DVR.

It works great but i have some problem:
Then stream works many days non-stop, after 3 days video start lagged and have lot of artefacts and delay time up to 1-2 minutes of video. Restart have fixed the problem. Temp of Pi 34C, memory and processor is in normal 12% and 92 Mb free - then lags go on.. Im try to use flags omxplayer -y -w -r and fifo options on random set (1mb to 4-5 mb) - not helpful, 2-3 days and lags start again. Im try to debug omxplayer but his used up to 200 mb in hour - this is imposible ti debug 2-3 days.. 

For details, please read my post on raspberry forum. In post im take a scrennshots and lags examples. Thank you.

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=56502&p=427916#p427916

**Comment by popcornmix** [comment] 2013-10-07 10:56
Duplicate of https://github.com/popcornmix/omxplayer/issues/64

**Closed as completed by popcornmix** 2013-10-07 10:56 UTC
