### ISSUE TITLE
2 instances: pause breaks sound

### ISSUE THREAD

**Issue by p3pp0** [huceke/omxplayer#239] opened 2015-02-23 12:26 UTC
Hey Guys,

i tried to get 2 videos play seamlesly (i know the loop function of omxplayer itself, but it is not useful for my special usecase)
Thus i found a solution to "precache" the second video via pause command, so i cant start it seamplessly after the first ends. Both instances run on different dbus_names, so i can control them via 2 different dbuscontrol.sh files

I now get the following issue:
If i start and pause immediatelly instance 2 while instance 1 is playing, everything works fine, but:
sound of instance 1 is stopping and added to instance 2, when unpaused

I hope u understand my issue, feel free to ask if not - sorry for bad english ;)

Thx a lot!

**Comment by popcornmix** [comment] 2015-02-23 15:59
Duplicate of https://github.com/popcornmix/omxplayer/issues/317

**Closed as completed by popcornmix** 2015-02-23 15:59 UTC
